### ISSUE TITLE
fecha or fireEvent causing typescript to not compile or throw error

### ISSUE THREAD

**Issue by reptilex** [custom-cards/custom-card-helpers#31] opened 2021-04-17 17:24 UTC
So I'm rather new to the ts world which might be the reason I'm doing something horribly wrong. But maybe I'm not and you can help me out. 
I have created a rather popular card here: https://github.com/reptilex/tesla-style-solar-power-card
The problem is that when I try to create a visual card editor following the boilercard template the card either does not compile with babel, it throws a punctuation error on the line where fecha and fireEvent are in js or has an error about a functiona not being named. It all disappears when I comment out the line [371 in my editor class](https://github.com/reptilex/tesla-style-solar-power-card/blob/4672a3b48e5876ab7d87c62b6056348b4767eda9/src/components/editor.ts#L371). I know it's not just terser having a hickup.
Could you take a look. Any pointers would be greatly appreciated. Here is my [package.json](https://github.com/reptilex/tesla-style-solar-power-card/blob/editor/package.json).

**Comment by marksie1988** [comment] 2021-05-15 22:03
I am also having the same issue as this, again if I comment out the fireEvent on the editor everything works again. 

Have you come to any solution yet?

**Comment by reptilex** [comment] 2021-05-16 07:33
I'm not well versed into all this ts js compiling stuff, so probably that's why I haven't figured out the cause. But although I haven't resolved the issue strangely enough when I re-implement the function in the component I used it and don't import it it works. So I just pasted this into my actual component:
`/**
 * Dispatches a custom event with an optional detail value.
 *
 * @param {string} type Name of event type.
 * @param {*=} detail Detail value containing event-specific
 *   payload.
 * @param {{ bubbles: (boolean|undefined),
 *           cancelable: (boolean|undefined),
 *           composed: (boolean|undefined) }=}
 *  options Object specifying options.  These may include:
 *  `bubbles` (boolean, defaults to `true`),
 *  `cancelable` (boolean, defaults to false), and
 *  `node` on which to fire the event (HTMLElement, defaults to `this`).
 * @return {Event} The new event that was fired.
 */
export const fireEvent = <HassEvent extends ValidHassDomEvent>(
  node: HTMLElement | Window,
  type: HassEvent,
  detail?: HASSDomEvents[HassEvent],
  options?: {
    bubbles?: boolean;
    cancelable?: boolean;
    composed?: boolean;
  }
) => {
  options = options || {};
  // @ts-ignore
  detail = detail === null || detail === undefined ? {} : detail;
  const event = new Event(type, {
    bubbles: options.bubbles === undefined ? true : options.bubbles,
    cancelable: Boolean(options.cancelable),
    composed: options.composed === undefined ? true : options.composed
  });
  (event as any).detail = detail;
  node.dispatchEvent(event);
  return event;
};`
Which I believe I just copy pasted from the actual class and now it works, so it surely has to do with some linkage and compilation ...

**Comment by marksie1988** [comment] 2021-05-16 18:32
Thanks for the info that helps :) 

I have also the errors im seeing in case this helps:

```
 10768 |     setGlobalDateI18n: setGlobalDateI18n,
  10769 |     setGlobalDateMasks: setGlobalDateMasks
> 10770 | };function(){try{(new Date).toLocaleDateString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleDateString(t,{year:"numeric",month:"long",day:"numeric"})}:function(t){return fecha.format(t,"mediumDate")};function(){try{(new Date).toLocaleString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleString(t,{year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"2-digit"})}:function(t){return fecha.format(t,"haDateTime")};function(){try{(new Date).toLocaleTimeString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleTimeString(t,{hour:"numeric",minute:"2-digit"})}:function(t){return fecha.format(t,"shortTime")};var C=function(e,t,a,r){r=r||{},a=null==a?{}:a;var n=new Event(t,{bubbles:void 0===r.bubbles||r.bubbles,cancelable:Boolean(r.cancelable),composed:void 0===r.composed||r.composed});return n.detail=a,e.dispatchEvent(n),n};var common = {
        |          ^ Unexpected token: punc (()
  10771 |       version: "Version",
  10772 |       show_warning: "Show Warning",
  10773 |       error: "Error",
```

Also this looks to be pointing towards an issue somewhere with the [DateTime files](https://github.com/custom-cards/custom-card-helpers/tree/master/src/datetime)

**Comment by marksie1988** [comment] 2021-09-16 21:38
Still not been able to find a fix for this, I'm finding this issue is not just from the fireevent but also if I implement the locale.timeformat 

Makes it impossible for me to move forward on a feature for my card but I can't for the life of me figure out the cause. 

It almost seems like when the code is microbundled it breaks for use with terser.

**Closed** 2021-10-21 19:49 UTC
